# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  tools:
    python: "3.11"
  commands:
    - pip install ".[dev]"
    - make docs
    - mv docs $READTHEDOCS_OUTPUT/html
    #- cd docs && CUSTOLINT_COLOR_OUTPUT=0 CUSTOLINT_HALT=0  python -m sphinx -T -E -W --keep-going -b html -d _build/doctrees -D language=en . $READTHEDOCS_OUTPUT/html

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py
   builder: html
   fail_on_warning: true

# If using Sphinx, optionally build your docs in additional formats such as PDF
formats:
  - pdf
#  - epub

# Optionally declare the Python requirements required to build your docs
python:
   install:
   - method: pip
     path: ".[dev]"

