name: Custolint
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: install python package
        run: make update_pip install_dev

      - name: validate
        run: git fetch && make validate && coverage xml

      - name: Upload coverage reports to Codecov with GitHub Action
        token: MU42A9NAT2
        uses: codecov/codecov-action@v3
        files: ./coverage.xml

      #- name: Report coverage
      #  run: ls -lah && curl -Os https://uploader.codecov.io/latest/linux/codecov
      #          && chmod +x codecov && ./codecov -f ./coverage.xml
