name: Custolint
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
        fetch-depth: 0

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: install python package
        run: make update_pip install_dev

      #- name: git fetch
      #  run: git fetch

      - name: validate
        run: make validate

      - name: create coverage xml
        run: coverage xml

      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v3
        with:
          #token: MU42A9NAT2
          flags: pytest
          files: ./coverage.xml
          fail_ci_if_error: true
          name: codecov
          verbose: true

      - name: Archive documentation
        run: export LANG=en_US.UTF-8 LC_ALL=$LANG && tar -cvf docs.tar docs

      - name: Upload documentation to artifactory
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: docs.tar

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: install python package
        run: make update_pip install_dev

      - name: Prepare wheel for PyPI
        run: make wheel

      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
